#' Plots a plot of class 'analyzerPlot'
#'
#' This function plots the plot generated by the library \code{analyzer}
#'
#' @param x a plot of class \code{analyzerPlot}
#' @param ... extra arguments if required
#'
#' @return Displays the plot
#'
#' @examples
#' # creating the plot
#' p <- plottr(x = mtcars$mpg, y = mtcars$disp, yclass = "numeric")
#' plot(p)
#'
#' @export
plot.analyzerPlot <- function(x, ...) {
  grid.newpage()
  grid.draw(x)
}


#' Method for print generic
#'
#' This function plots the plot generated by the library \code{analyzer}
#'
#' @param x a plot of class \code{analyzerPlot}
#'
#' @return Displays the plot
#'
#' @examples
#' # creating the plot
#' p <- plottr(x = mtcars$mpg, y = mtcars$disp, yclass = "numeric")
#' p
#'
#' @export
print.analyzerPlot <- function(x) {
  plot(x)
}
