#' Creates plots for all the variables in a data.frame
#'
#' \code{plottrWrapper} is a wrapper built on \code{plottr} to
#' create plots for all the variables
#'
#' This function calls [plottr()] multiple times to create the
#' plots for all the variables.
#' For more information on plots, look into \code{plottr}
#'
#' @param tb a data.frame
#' @param yvar a string showing the repsonse (dependent) variable
#'  name. Can be \code{NULL} if reponse
#' variable is not present
#' @param xclasses a vector of length \code{= ncol(tb)} with
#' the data type of all the columns.
#' Can be \code{NULL}, in such case function assigns a class
#' to each column. Look into [plottr()]
#' for more details.
#' @param yclass class of response variable. Can be \code{NULL},
#' but must have value
#' when \code{yvar} is not \code{NULL}. Value can be
#' \code{'factor'} or \code{'numeric'}
#' @param printall (logical) Whether user wants to show the plots.
#' Setting this as \code{FALSE}
#' will only returns a list of plots silently.
#' @param binwidth.x,binwidth.y binwidth for \code{x} and \code{y}
#' used for generating the histogram.
#' If there are \code{NULL}, then ggplot2 assigns the value
#' on its own. Look at \code{binwidth} of ggplot for more information
#' @param callasfactor minimum unique values needed for \code{x}
#'  to be considered as numeric.
#' See details of [plottr()] for more information.
#' @param inc.density (logical) Whether density plot is needed
#' along with histogram.
#'
#' @return A list of plots for all the variables. Each plot will
#' have the class \code{analyzerPlot}
#' and can be displayed using \code{plot()}. If \code{printall = TRUE},
#' then all plots will also
#' be displayed.
#'
#' @examples
#' # simple use
#' p <- plottrWrapper(mtcars)
#' # To display one of the plot for variable 'mpg'
#' plot(p$mpg)
#'
#' # In case displaying all the plots is needed
#' p <- plottrWrapper(mtcars, printall = TRUE)
#'
#' # With assuming 'mpg' as a dependent variable
#' p <- plottrWrapper(mtcars, yvar = "mpg", yclass = "numeric")
#' plot(p$disp)
#'
#' @export

plottrWrapper <- function(tb, yvar = NULL, xclasses = NULL, yclass = NULL,
                          printall = F, binwidth.x = NULL, binwidth.y = NULL,
                          callasfactor = 1, inc.density = F) {

  if (!is.null(yvar)) {
    if (is.null(yclass)) {
      stop("Pass the class of y as either 'numeric' or 'factor'")
    } else if(!yclass %in% c("numeric", "factor")) {
      stop("Pass the class of y as either 'numeric' or 'factor'")
    }
  }

  tb <- data.frame(tb)
  plots = list()
  xvars <- colnames(tb)
  y <- NULL
  if (!is.null(yvar)) y <- tb[, yvar]
  j = 1
  for (i in xvars) {
    print(i)
    a <- tryCatch(plottr(x = tb[,i], y = y, xclass=xclasses[j], yclass=yclass,
                         xname = i, yname = yvar, binwidth.x = binwidth.x,
                         binwidth.y = binwidth.y, callasfactor = callasfactor),
                  error=function(e) {return(NULL)})

    plots[i] <- list(a)
    j=j+1
  }

  if (printall) {
    for (i in plots) {
      if(!is.null(i)){
        plot(i)
      } else {
        cat("This plot failed to be generated. Try 'plottr' for this variable.")
      }
      readline(prompt="Press [enter] to continue and wait for the plot to appear")
    }
  }
  invisible(plots)
}

#' Plots a plot of class 'analyzerPlot'
#'
#' This function plots the plot generated by the library \code{analyzer}
#'
#' @param x a plot of class \code{analyzerPlot}
#' @param ... extra arguments if required
#'
#' @return Displays the plot
#'
#' @examples
#' # creating the plot
#' p <- plottr(x = mtcars$mpg, y = mtcars$disp, yclass = "numeric")
#' plot(p)
#'
#' @export

plot.analyzerPlot <- function(x, ...) {
  grid.newpage()
  grid.draw(x)
}
